# Data Wrangling

In [ ]:
import requests
import json
import pandas as pd
import numpy as np
import xmltodict

peloton_username = 'PELOTON_USERNAME'
peloton_pw = 'PELOTON_PASSWORD'

## Getting Peloton Data

In [ ]:
# Get workouts from Peloton API
s = requests.Session()
base_url = 'https://api.onepeloton.com'
payload = {'username_or_email': peloton_username, 'password': peloton_pw}
s.post(base_url + '/auth/login', json=payload)
userID = s.get(base_url + '/api/me').json()['id']
workouts = json.loads(json.dumps(s.get(base_url + '/api/user/' + userID + '/workouts?limit=1000').json()).replace('null', '""'))
instructors = json.loads(json.dumps(s.get(base_url + '/api/instructor?limit=100').json()).replace('null', '""'))['data']

In [ ]:
with open('../Data/workouts.txt', 'w') as outfile:
    json.dump(workouts, outfile)

with open('../Data/instructors.txt', 'w') as outfile:
    json.dump(instructors, outfile)

In [ ]:
workout_df = pd.json_normalize(workouts['data'])

In [ ]:
workout_df.head()

,created_at,device_type,end_time,fitbit_id,fitness_discipline,has_pedaling_metrics,has_leaderboard_metrics,id,is_total_work_personal_record,metrics_type,...,total_music_audio_buffer_seconds,created,device_time_created_at,effort_zones.total_effort_points,effort_zones.heart_rate_zone_durations.heart_rate_z1_duration,effort_zones.heart_rate_zone_durations.heart_rate_z2_duration,effort_zones.heart_rate_zone_durations.heart_rate_z3_duration,effort_zones.heart_rate_zone_durations.heart_rate_z4_duration,effort_zones.heart_rate_zone_durations.heart_rate_z5_duration,effort_zones
0,1621557152,home_bike_v1,1621557453,,stretching,False,False,6151aa7f53934d51912dc715d7d4b1d4,False,,...,,1621557152,1621539152,4.78,0.0,120.0,179.0,0.0,0.0,NaN
1,1621553381,home_bike_v1,1621557040,,cycling,True,True,eea491334f784759a6baf2fff47905d2,False,cycling,...,,1621553381,1621535381,122.62,48.0,230.0,628.0,1566.0,1122.0,NaN
2,1621465919,home_bike_v1,1621466220,,stretching,False,False,518a08e2501c437b996df94baec94e11,False,,...,,1621465919,1621447919,6.03,0.0,41.0,235.0,23.0,0.0,NaN
3,1621463062,home_bike_v1,1621465782,,cycling,True,True,be933127516d4856a62d0fc80ae110d0,False,cycling,...,,1621463062,1621445062,95.75,56.0,175.0,244.0,1335.0,886.0,NaN
4,1621304492,home_bike_v1,1621304793,,stretching,False,False,8d95a18a4e774bbcb49a0c10486b0436,False,,...,,1621304492,1621286492,3.44,0.0,252.0,46.0,0.0,0.0,NaN

In [ ]:
instructor_df = pd.json_normalize(instructors)

In [ ]:
instructor_df.head()

,id,bio,short_bio,coach_type,is_filterable,is_instructor_group,is_visible,is_announced,list_order,featured_profile,...,ios_instructor_list_display_image_url,about_image_url,image_url,jumbotron_url,jumbotron_url_dark,jumbotron_url_ios,web_instructor_list_gif_image_url,instructor_hero_image_url,workout_share_images,fitness_disciplines
0,b8c2734e18a7496fa146b3a42465da67,"To Aditi, yoga goes beyond movement and can br...",,peloton_coach,True,False,True,True,17,True,...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,"[{'fitness_discipline': 'cycling', 'image_url'...","[meditation, yoga]"
1,f962a2b1b34d424cabab73bef81bc8db,Adrian is a powerhouse instructor with an unex...,Adrian is a powerhouse instructor with an unex...,peloton_coach,True,False,True,True,18,True,...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,"[{'fitness_discipline': 'cycling', 'image_url'...","[walking, strength, stretching, circuit, cardi..."
2,a8c56f162c964e9392568bc13828a3fb,"When Anna first turned to yoga, she felt a swi...",“Look for balance but always be willing to fall”,peloton_coach,True,False,True,True,19,True,...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,"[{'fitness_discipline': 'cycling', 'image_url'...","[meditation, yoga]"
3,2e57092bee334c8c8dcb9fe16ba5308c,"Alex Toussaint has a love for fitness, teamwor...","""Feel good. Look good. Do better! \r\n… Trust ...",peloton_coach,True,False,True,True,21,True,...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,"[{'fitness_discipline': 'cycling', 'image_url'...",[cycling]
4,731d7b7f6b414a49892c21f01e25317d,"As a model, dancer, certified health coach, ho...","They say the early bird gets the worm, but the...",peloton_coach,True,False,True,True,22,True,...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,https://s3.amazonaws.com/workout-metric-images...,,https://s3.amazonaws.com/workout-metric-images...,"[{'fitness_discipline': 'cycling', 'image_url'...",[cycling]

In [ ]:
#build workout summary dataframe based on workoutids
workout_ids = list(workout_df['id'])

workout_summary = []
workout_performance = []

for workout_id in workout_ids:
    summary_dict = json.loads(json.dumps(s.get(base_url + '/api/workout/' + workout_id).json()).replace('null', '""'))
    performance_dict = json.loads(json.dumps(s.get(base_url + '/api/workout/' + workout_id + '/performance_graph?every_n=1000').json()).replace('null', '""'))
    performance_dict['id']=workout_id
    workout_summary.append(summary_dict)
    workout_performance.append(performance_dict)

In [ ]:
with open('../Data/workout_summary.txt', 'w') as outfile:
    json.dump(workout_summary, outfile)
    
with open('../Data/workout_performance.txt', 'w') as outfile:
    json.dump(workout_performance, outfile)

In [ ]:
summary_df = pd.json_normalize(workout_summary)

In [ ]:
list(summary_df.columns)

['created_at',
 'device_type',
 'end_time',
 'fitbit_id',
 'fitness_discipline',
 'has_pedaling_metrics',
 'has_leaderboard_metrics',
 'id',
 'is_total_work_personal_record',
 'metrics_type',
 'name',
 'peloton_id',
 'platform',
 'start_time',
 'strava_id',
 'status',
 'timezone',
 'title',
 'total_work',
 'user_id',
 'workout_type',
 'total_video_watch_time_seconds',
 'total_video_buffering_seconds',
 'v2_total_video_watch_time_seconds',
 'v2_total_video_buffering_seconds',
 'total_music_audio_play_seconds',
 'total_music_audio_buffer_seconds',
 'created',
 'device_time_created_at',
 'is_skip_intro_available',
 'average_effort_score',
 'achievement_templates',
 'leaderboard_rank',
 'total_leaderboard_users',
 'device_type_display_name',
 'ride.availability.is_available',
 'ride.availability.reason',
 'ride.class_type_ids',
 'ride.content_provider',
 'ride.content_format',
 'ride.description',
 'ride.difficulty_estimate',
 'ride.overall_estimate',
 'ride.difficulty_rating_avg',
 'ride.difficulty_rating_count',
 'ride.difficulty_level',
 'ride.duration',
 'ride.equipment_ids',
 'ride.equipment_tags',
 'ride.extra_images',
 'ride.fitness_discipline',
 'ride.fitness_discipline_display_name',
 'ride.has_closed_captions',
 'ride.has_pedaling_metrics',
 'ride.home_peloton_id',
 'ride.id',
 'ride.image_url',
 'ride.instructor_id',
 'ride.individual_instructor_ids',
 'ride.is_archived',
 'ride.is_closed_caption_shown',
 'ride.is_explicit',
 'ride.has_free_mode',
 'ride.is_live_in_studio_only',
 'ride.language',
 'ride.origin_locale',
 'ride.length',
 'ride.live_stream_id',
 'ride.live_stream_url',
 'ride.location',
 'ride.metrics',
 'ride.original_air_time',
 'ride.overall_rating_avg',
 'ride.overall_rating_count',
 'ride.pedaling_start_offset',
 'ride.pedaling_end_offset',
 'ride.pedaling_duration',
 'ride.rating',
 'ride.ride_type_id',
 'ride.ride_type_ids',
 'ride.sample_vod_stream_url',
 'ride.scheduled_start_time',
 'ride.series_id',
 'ride.sold_out',
 'ride.studio_peloton_id',
 'ride.title',
 'ride.total_ratings',
 'ride.total_in_progress_workouts',
 'ride.total_workouts',
 'ride.vod_stream_url',
 'ride.vod_stream_id',
 'ride.captions',
 'ride.join_tokens.on_demand',
 'ride.flags',
 'ride.is_dynamic_video_eligible',
 'ride.is_fixed_distance',
 'ride.dynamic_video_recorded_speed_in_mph',
 'ride.thumbnail_title',
 'ride.thumbnail_location',
 'ride.distance',
 'ride.distance_unit',
 'ride.distance_display_value',
 'ride.excluded_platforms',
 'total_heart_rate_zone_durations.heart_rate_z1_duration',
 'total_heart_rate_zone_durations.heart_rate_z2_duration',
 'total_heart_rate_zone_durations.heart_rate_z3_duration',
 'total_heart_rate_zone_durations.heart_rate_z4_duration',
 'total_heart_rate_zone_durations.heart_rate_z5_duration',
 'ftp_info.ftp',
 'ftp_info.ftp_source',
 'ftp_info.ftp_workout_id',
 'total_heart_rate_zone_durations']

In [ ]:
performance_df = pd.json_normalize(workout_performance)

In [ ]:
list(performance_df.columns)

['duration',
 'is_class_plan_shown',
 'segment_list',
 'seconds_since_pedaling_start',
 'average_summaries',
 'summaries',
 'metrics',
 'has_apple_watch_metrics',
 'location_data',
 'is_location_data_accurate',
 'id',
 'target_metrics_performance_data.target_metrics',
 'target_metrics_performance_data.time_in_metric',
 'effort_zones.total_effort_points',
 'effort_zones.heart_rate_zone_durations.heart_rate_z1_duration',
 'effort_zones.heart_rate_zone_durations.heart_rate_z2_duration',
 'effort_zones.heart_rate_zone_durations.heart_rate_z3_duration',
 'effort_zones.heart_rate_zone_durations.heart_rate_z4_duration',
 'effort_zones.heart_rate_zone_durations.heart_rate_z5_duration',
 'effort_zones',
 'target_performance_metrics.target_graph_metrics',
 'target_performance_metrics.cadence_time_in_range',
 'target_performance_metrics.resistance_time_in_range']

In [ ]:
summary_df.head()

,created_at,device_type,end_time,fitbit_id,fitness_discipline,has_pedaling_metrics,has_leaderboard_metrics,id,is_total_work_personal_record,metrics_type,...,ride.excluded_platforms,total_heart_rate_zone_durations.heart_rate_z1_duration,total_heart_rate_zone_durations.heart_rate_z2_duration,total_heart_rate_zone_durations.heart_rate_z3_duration,total_heart_rate_zone_durations.heart_rate_z4_duration,total_heart_rate_zone_durations.heart_rate_z5_duration,ftp_info.ftp,ftp_info.ftp_source,ftp_info.ftp_workout_id,total_heart_rate_zone_durations
0,1621557152,home_bike_v1,1621557453,,stretching,False,False,6151aa7f53934d51912dc715d7d4b1d4,False,,...,"[aurora, home_tread, studio_tread]",57.0,842.0,861.0,31.0,0.0,0,,,NaN
1,1621553381,home_bike_v1,1621557040,,cycling,True,True,eea491334f784759a6baf2fff47905d2,False,cycling,...,[],NaN,NaN,NaN,NaN,NaN,114,ftp_workout_source,71c5c262606e4615a6cd3594dfd02692,
2,1621465919,home_bike_v1,1621466220,,stretching,False,False,518a08e2501c437b996df94baec94e11,False,,...,"[aurora, studio_tread, home_tread]",57.0,842.0,861.0,31.0,0.0,0,,,NaN
3,1621463062,home_bike_v1,1621465782,,cycling,True,True,be933127516d4856a62d0fc80ae110d0,False,cycling,...,[],185.0,614.0,2063.0,4342.0,886.0,114,ftp_workout_source,71c5c262606e4615a6cd3594dfd02692,NaN
4,1621304492,home_bike_v1,1621304793,,stretching,False,False,8d95a18a4e774bbcb49a0c10486b0436,False,,...,"[aurora, home_tread, studio_tread]",57.0,842.0,861.0,31.0,0.0,0,,,NaN

In [ ]:
performance_df.head()

,duration,is_class_plan_shown,segment_list,seconds_since_pedaling_start,average_summaries,summaries,metrics,has_apple_watch_metrics,location_data,is_location_data_accurate,...,effort_zones.total_effort_points,effort_zones.heart_rate_zone_durations.heart_rate_z1_duration,effort_zones.heart_rate_zone_durations.heart_rate_z2_duration,effort_zones.heart_rate_zone_durations.heart_rate_z3_duration,effort_zones.heart_rate_zone_durations.heart_rate_z4_duration,effort_zones.heart_rate_zone_durations.heart_rate_z5_duration,effort_zones,target_performance_metrics.target_graph_metrics,target_performance_metrics.cadence_time_in_range,target_performance_metrics.resistance_time_in_range
0,300,True,"[{'id': 'd05373cda17e464985f56c16ec04825e', 'l...","[1, 300]",[],"[{'display_name': 'Calories', 'display_unit': ...","[{'display_name': 'Heart Rate', 'display_unit'...",False,[],,...,4.78,0.0,120.0,179.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3600,True,"[{'id': '8ee24e5da3734fe9a13cfaa51b07dae9', 'l...","[1, 1001, 2001, 3001, 3598]","[{'display_name': 'Avg Output', 'display_unit'...","[{'display_name': 'Total Output', 'display_uni...","[{'display_name': 'Output', 'display_unit': 'w...",False,[],,...,122.62,48.0,230.0,628.0,1566.0,1122.0,NaN,NaN,NaN,NaN
2,300,False,"[{'id': '7b563929a4254f5aba1004a44950d443', 'l...","[1, 300]",[],"[{'display_name': 'Calories', 'display_unit': ...","[{'display_name': 'Heart Rate', 'display_unit'...",False,[],,...,6.03,0.0,41.0,235.0,23.0,0.0,NaN,NaN,NaN,NaN
3,2700,True,"[{'id': '73682ab65f474accb39f8a6ea1ab9303', 'l...","[2, 1002, 2002, 2700]","[{'display_name': 'Avg Output', 'display_unit'...","[{'display_name': 'Total Output', 'display_uni...","[{'display_name': 'Output', 'display_unit': 'w...",False,[],,...,95.75,56.0,175.0,244.0,1335.0,886.0,NaN,NaN,NaN,NaN
4,300,True,"[{'id': 'd05373cda17e464985f56c16ec04825e', 'l...","[3, 300]",[],"[{'display_name': 'Calories', 'display_unit': ...","[{'display_name': 'Heart Rate', 'display_unit'...",False,[],,...,3.42,0.0,252.0,45.0,0.0,0.0,NaN,NaN,NaN,NaN

## Getting Apple Health Data

In [ ]:
input_path = ''
with open('../Data/export.xml', 'r') as xml_file:
    input_data = xmltodict.parse(xml_file.read())

In [ ]:
records_list = input_data['HealthData']['Record']

In [ ]:
health_df = pd.DataFrame(records_list)

In [ ]:
health_df.columns

Index(['@type', '@sourceName', '@sourceVersion', '@unit', '@creationDate',
       '@startDate', '@endDate', '@value', 'MetadataEntry', '@device',
       'HeartRateVariabilityMetadataList'],
      dtype='object')

In [ ]:
health_df['@type'].unique()

array(['HKQuantityTypeIdentifierBodyMassIndex',
       'HKQuantityTypeIdentifierHeight',
       'HKQuantityTypeIdentifierBodyMass',
       'HKQuantityTypeIdentifierHeartRate',
       'HKQuantityTypeIdentifierOxygenSaturation',
       'HKQuantityTypeIdentifierBodyFatPercentage',
       'HKQuantityTypeIdentifierLeanBodyMass',
       'HKQuantityTypeIdentifierStepCount',
       'HKQuantityTypeIdentifierDistanceWalkingRunning',
       'HKQuantityTypeIdentifierBasalEnergyBurned',
       'HKQuantityTypeIdentifierActiveEnergyBurned',
       'HKQuantityTypeIdentifierFlightsClimbed',
       'HKQuantityTypeIdentifierDietaryFatTotal',
       'HKQuantityTypeIdentifierDietaryFatPolyunsaturated',
       'HKQuantityTypeIdentifierDietaryFatMonounsaturated',
       'HKQuantityTypeIdentifierDietaryFatSaturated',
       'HKQuantityTypeIdentifierDietaryCholesterol',
       'HKQuantityTypeIdentifierDietarySodium',
       'HKQuantityTypeIdentifierDietaryCarbohydrates',
       'HKQuantityTypeIdentifierDietaryFiber',
       'HKQuantityTypeIdentifierDietarySugar',
       'HKQuantityTypeIdentifierDietaryEnergyConsumed',
       'HKQuantityTypeIdentifierDietaryProtein',
       'HKQuantityTypeIdentifierDietaryVitaminC',
       'HKQuantityTypeIdentifierDietaryCalcium',
       'HKQuantityTypeIdentifierDietaryIron',
       'HKQuantityTypeIdentifierDietaryPotassium',
       'HKQuantityTypeIdentifierAppleExerciseTime',
       'HKQuantityTypeIdentifierWaistCircumference',
       'HKQuantityTypeIdentifierRestingHeartRate',
       'HKQuantityTypeIdentifierWalkingHeartRateAverage',
       'HKQuantityTypeIdentifierHeadphoneAudioExposure',
       'HKQuantityTypeIdentifierWalkingDoubleSupportPercentage',
       'HKQuantityTypeIdentifierSixMinuteWalkTestDistance',
       'HKQuantityTypeIdentifierAppleStandTime',
       'HKQuantityTypeIdentifierWalkingSpeed',
       'HKQuantityTypeIdentifierWalkingStepLength',
       'HKQuantityTypeIdentifierWalkingAsymmetryPercentage',
       'HKQuantityTypeIdentifierStairAscentSpeed',
       'HKQuantityTypeIdentifierStairDescentSpeed',
       'HKDataTypeSleepDurationGoal',
       'HKCategoryTypeIdentifierSleepAnalysis',
       'HKCategoryTypeIdentifierAppleStandHour',
       'HKCategoryTypeIdentifierMindfulSession',
       'HKQuantityTypeIdentifierHeartRateVariabilitySDNN'], dtype=object)

In [ ]:
health_df[(health_df['@type'] == 'HKQuantityTypeIdentifierBodyMass') & (health_df['@sourceName'] == 'Renpho')]

,@type,@sourceName,@sourceVersion,@unit,@creationDate,@startDate,@endDate,@value,MetadataEntry,@device,HeartRateVariabilityMetadataList
357,HKQuantityTypeIdentifierBodyMass,Renpho,1,lb,2020-05-25 11:30:24 -0500,2019-09-06 06:49:40 -0500,2019-09-06 06:49:40 -0500,180.2,NaN,NaN,NaN
358,HKQuantityTypeIdentifierBodyMass,Renpho,1,lb,2020-05-25 11:30:32 -0500,2019-09-05 07:04:36 -0500,2019-09-05 07:04:36 -0500,179.8,NaN,NaN,NaN
359,HKQuantityTypeIdentifierBodyMass,Renpho,1,lb,2020-05-25 11:30:42 -0500,2019-09-03 06:26:54 -0500,2019-09-03 06:26:54 -0500,180.6,NaN,NaN,NaN
360,HKQuantityTypeIdentifierBodyMass,Renpho,1,lb,2020-05-25 11:30:43 -0500,2019-09-02 04:51:40 -0500,2019-09-02 04:51:40 -0500,172.6,NaN,NaN,NaN
361,HKQuantityTypeIdentifierBodyMass,Renpho,1,lb,2020-05-25 11:30:43 -0500,2019-08-29 06:40:13 -0500,2019-08-29 06:40:13 -0500,177.6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
753,HKQuantityTypeIdentifierBodyMass,Renpho,2,lb,2021-05-14 08:05:48 -0500,2021-05-14 07:54:05 -0500,2021-05-14 07:54:05 -0500,190.4,NaN,NaN,NaN
755,HKQuantityTypeIdentifierBodyMass,Renpho,2,lb,2021-05-15 08:07:05 -0500,2021-05-15 08:06:38 -0500,2021-05-15 08:06:38 -0500,191.2,NaN,NaN,NaN
758,HKQuantityTypeIdentifierBodyMass,Renpho,2,lb,2021-05-16 13:23:46 -0500,2021-05-16 09:03:02 -0500,2021-05-16 09:03:02 -0500,190.6,NaN,NaN,NaN
760,HKQuantityTypeIdentifierBodyMass,Renpho,2,lb,2021-05-18 06:47:24 -0500,2021-05-18 06:47:23 -0500,2021-05-18 06:47:23 -0500,191.8,NaN,NaN,NaN
761,HKQuantityTypeIdentifierBodyMass,Renpho,2,lb,2021-05-18 06:47:24 -0500,2021-05-17 07:56:48 -0500,2021-05-17 07:56:48 -0500,192,NaN,NaN,NaN

In [ ]:
health_df[health_df['@sourceName'] == 'Renpho']['@type'].unique()

array(['HKQuantityTypeIdentifierBodyMassIndex',
       'HKQuantityTypeIdentifierHeight',
       'HKQuantityTypeIdentifierBodyMass',
       'HKQuantityTypeIdentifierBodyFatPercentage',
       'HKQuantityTypeIdentifierLeanBodyMass',
       'HKQuantityTypeIdentifierBasalEnergyBurned',
       'HKQuantityTypeIdentifierWaistCircumference'], dtype=object)

In [ ]:
weight_df = health_df[((health_df['@type'] == 'HKQuantityTypeIdentifierBodyMass') | (health_df['@type'] == 'HKQuantityTypeIdentifierLeanBodyMass')) & (health_df['@sourceName'] == 'Renpho')][['@type','@startDate', '@value']]

In [ ]:
weight_df

                                       @type                 @startDate @value
357         HKQuantityTypeIdentifierBodyMass  2019-09-06 06:49:40 -0500  180.2
358         HKQuantityTypeIdentifierBodyMass  2019-09-05 07:04:36 -0500  179.8
359         HKQuantityTypeIdentifierBodyMass  2019-09-03 06:26:54 -0500  180.6
360         HKQuantityTypeIdentifierBodyMass  2019-09-02 04:51:40 -0500  172.6
361         HKQuantityTypeIdentifierBodyMass  2019-08-29 06:40:13 -0500  177.6
...                                      ...                        ...    ...
133370  HKQuantityTypeIdentifierLeanBodyMass  2021-05-14 07:54:05 -0500  123.6
133371  HKQuantityTypeIdentifierLeanBodyMass  2021-05-15 08:06:38 -0500  123.8
133372  HKQuantityTypeIdentifierLeanBodyMass  2021-05-16 09:03:02 -0500  123.8
133373  HKQuantityTypeIdentifierLeanBodyMass  2021-05-18 06:47:23 -0500  124.2
133374  HKQuantityTypeIdentifierLeanBodyMass  2021-05-17 07:56:48 -0500  124.2

[701 rows x 3 columns]

In [ ]:
data_point_summary = weight_df.groupby('@startDate').count()

In [ ]:
data_point_summary[data_point_summary['@value'] > 2]
# we have two datapoints that should be collected each day

                           @type  @value
@startDate
2020-05-25 11:30:22 -0500      4       4
2020-05-25 11:30:23 -0500      4       4
2020-05-25 11:30:25 -0500      4       4
2020-05-25 11:30:26 -0500      4       4
2020-06-22 21:45:08 -0500      6       6
2020-06-22 21:45:09 -0500      6       6
2020-06-22 21:45:10 -0500      6       6
2020-07-26 08:15:04 -0500      4       4
2020-08-07 07:15:08 -0500      6       6
2021-01-24 12:22:50 -0500      4       4
2021-01-24 12:22:51 -0500      8       8
2021-01-24 12:22:53 -0500      4       4
2021-01-24 12:22:54 -0500      6       6
2021-03-15 07:10:43 -0500      4       4
2021-04-14 08:06:26 -0500      4       4

In [ ]:
weight_df[weight_df['@startDate'] == '2021-04-14 08:06:26 -0500']
# looksl ike duplicates - review another date

                                       @type                 @startDate @value
690         HKQuantityTypeIdentifierBodyMass  2021-04-14 08:06:26 -0500  193.6
691         HKQuantityTypeIdentifierBodyMass  2021-04-14 08:06:26 -0500  193.6
133341  HKQuantityTypeIdentifierLeanBodyMass  2021-04-14 08:06:26 -0500  124.4
133342  HKQuantityTypeIdentifierLeanBodyMass  2021-04-14 08:06:26 -0500  124.4

In [ ]:
weight_df[weight_df['@startDate'] == '2021-01-24 12:22:54 -0500']

                                       @type                 @startDate @value
628         HKQuantityTypeIdentifierBodyMass  2021-01-24 12:22:54 -0500    193
629         HKQuantityTypeIdentifierBodyMass  2021-01-24 12:22:54 -0500    193
630         HKQuantityTypeIdentifierBodyMass  2021-01-24 12:22:54 -0500    193
133295  HKQuantityTypeIdentifierLeanBodyMass  2021-01-24 12:22:54 -0500  146.6
133296  HKQuantityTypeIdentifierLeanBodyMass  2021-01-24 12:22:54 -0500  146.6
133297  HKQuantityTypeIdentifierLeanBodyMass  2021-01-24 12:22:54 -0500  146.6

In [ ]:
weight_df = weight_df.drop_duplicates().reset_index(drop=True)

In [ ]:
weight_df.head()

                              @type                 @startDate @value
0  HKQuantityTypeIdentifierBodyMass  2019-09-06 06:49:40 -0500  180.2
1  HKQuantityTypeIdentifierBodyMass  2019-09-05 07:04:36 -0500  179.8
2  HKQuantityTypeIdentifierBodyMass  2019-09-03 06:26:54 -0500  180.6
3  HKQuantityTypeIdentifierBodyMass  2019-09-02 04:51:40 -0500  172.6
4  HKQuantityTypeIdentifierBodyMass  2019-08-29 06:40:13 -0500  177.6

In [ ]:
#save weight_df
weight_df.to_csv('../Data/weight.csv', index=False)

In [ ]:
weight_df.shape

(657, 3)

In [ ]:
workout_df.shape

(630, 36)

In [ ]:
instructor_df.shape

(40, 38)

In [ ]:
summary_df.shape

(630, 112)

In [ ]:
performance_df.shape

(630, 23)